import React, { useState } from 'react';

/**
 * QuizView — interactive multiple-choice quiz generated by CrewAI.
 *
 * Props:
 *   questions  {Array<{question, options, correct_answer, explanation}>}
 */
const QuizView = ({ questions }) => {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selected, setSelected] = useState(null);       // e.g. "A"
  const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);

  if (!questions || questions.length === 0) return null;

  const q = questions[currentIdx];

  const letterFor = (idx) => ['A', 'B', 'C', 'D'][idx] ?? String(idx);

  const handleSelect = (letter) => {
    if (revealed) return;
    setSelected(letter);
  };

  const handleCheck = () => {
    if (!selected) return;
    setRevealed(true);
    if (selected === q.correct_answer) setScore((s) => s + 1);
  };

  const handleNext = () => {
    if (currentIdx + 1 >= questions.length) {
      setFinished(true);
      return;
    }
    setCurrentIdx((i) => i + 1);
    setSelected(null);
    setRevealed(false);
  };

  const handleRestart = () => {
    setCurrentIdx(0);
    setSelected(null);
    setRevealed(false);
    setScore(0);
    setFinished(false);
  };

  // ── Results screen ───────────────────────────────────────────────────────
  if (finished) {
    const pct = Math.round((score / questions.length) * 100);
    return (
      <div className="quiz-results">
        <div className="result-score">{pct}%</div>
        <div className="result-label">
          {pct >= 80 ? '🎉 Excellent!' : pct >= 50 ? '👍 Good effort!' : '📚 Keep studying!'}
        </div>
        <div className="result-sub">
          You got {score} out of {questions.length} correct
        </div>
        <button className="btn-sm btn-primary" onClick={handleRestart}>
          Retake Quiz
        </button>
      </div>
    );
  }

  // ── Question screen ──────────────────────────────────────────────────────
  return (
    <div className="quiz-container">
      <div className="quiz-header">
        <span className="quiz-progress">
          Question <strong>{currentIdx + 1}</strong> / {questions.length}
        </span>
        <span className="quiz-score-badge">Score: {score}</span>
      </div>

      <div className="question-card">
        <div className="question-num">Question {currentIdx + 1}</div>
        <div className="question-text">{q.question}</div>

        <div className="options-list">
          {(q.options || []).map((opt, i) => {
            const letter = letterFor(i);
            let cls = 'option-btn';
            if (revealed) {
              if (letter === q.correct_answer)          cls += ' correct';
              else if (letter === selected)             cls += ' incorrect';
            } else if (letter === selected) {
              cls += ' selected';
            }
            return (
              <button
                key={i}
                className={cls}
                onClick={() => handleSelect(letter)}
                disabled={revealed}
              >
                <span className="option-letter">{letter}</span>
                <span>{opt.replace(/^[A-D]\)\s*/, '')}</span>
              </button>
            );
          })}
        </div>

        {revealed && q.explanation && (
          <div className="explanation-box">💡 {q.explanation}</div>
        )}
      </div>

      <div className="quiz-nav">
        {!revealed ? (
          <button
            className="btn-sm btn-primary"
            disabled={!selected}
            onClick={handleCheck}
          >
            Check Answer
          </button>
        ) : (
          <button className="btn-sm btn-primary" onClick={handleNext}>
            {currentIdx + 1 >= questions.length ? 'See Results' : 'Next Question →'}
          </button>
        )}
      </div>
    </div>
  );
};

export default QuizView;
